config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get '/search', to: 'searches#searche'
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource:favorites,only:[:create, :destroy]
    resources:book_comments,only:[:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource:relationship,only:[:create, :destroy]
    get "relationships/follow_list"
    get "relationships/follower_list"
  end
  resources :chats, only: [:show,:create]

  resources:groups,only:[:new,:create,:index,:edit,:update,:show,:destroy]
  # get '/search'=>'searches#search',as:"search"
  # get '/search', to: 'searchs#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  belongs_to:user
  has_many:favorites,dependent: :destroy
  has_many:like_user,through: :favorites,source: :user

  has_many:book_comments,dependent: :destroy
  # def get_profile_image
  #   (profile_image.attached?) ? profile_image : 'no_image.jpg'
  # end


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to:user
  belongs_to:book
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to:user
  belongs_to:room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to:user
  belongs_to:book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many:group_users,dependent: :destroy
  has_many:users,through: :group_users
  has_one_attached:group_image
  def get_group_image(width,height)
    unless group_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      group_image.attach(io:File.open(file_path),filename:"default-image.jpg",content_type:"image/jpg")
    end
      group_image.variant(resize_to_limit:[width,height]).processed
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to:user
  belongs_to:group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to:follower,class_name: "User"
  belongs_to:followed,class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many:chats,dependent: :destroy
  has_many:user_rooms,dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:books,dependent: :destroy
  has_many:favorites,dependent: :destroy
  has_many:book_comments,dependent: :destroy

  has_many:follower,class_name: "Relationship" , foreign_key: "follower_id",dependent: :destroy
  has_many:followed,class_name: "Relationship" , foreign_key: "followed_id",dependent: :destroy

  has_many:followers,through: :follower,source: :followed
  has_many:followeds,through: :followed,source: :follower

  has_many:group_users,dependent: :destroy
  has_many:groups,through: :group_users

  has_many:user_rooms,dependent: :destroy
  has_many:chats,dependent: :destroy

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,length:{ maximum: 50 }



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to:user
  belongs_to:room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit]
  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @books = Book.new
    @comment = BookComment.new
    @today_books = Book.where(created_at: Date.current)
  end

  def index
    to=Time.current
    from=(to - 6.day)
    @book = Book.new
    @books = Book.includes(:like_user).sort{|a,b|
     b.like_user.includes(:favorites).where(created_at: from...to).size <=>
     a.like_user.includes(:favorites).where(created_at: from...to).size}
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      @book = Book.new
      @books = Book.all
      redirect_to books_path
    end
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_room = UserRoom.find_by(user_id: @user.id,room_id: rooms)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end
  def create
    # if. 参加を押した場合
    if params[:key]=="value"
      group = Group.find(params[:group])
      @user_room = GroupUser.new
      @user_room.user_id=current_user.id

      @user_room.group_id = group.id
      @user_room.save
      redirect_to groups_path
  
    else
      group = Group.new(group_params)
      group.owner_id = current_user.id
      group.save
      @user_room = GroupUser.new
      @user_room.user_id=current_user.id
      @user_room.group_id = group.id
      @user_room.save
      redirect_to groups_path
    end
  end
  def destroy
    # グループを抜ける処理
    if params[:key]=="value"
      user_room = GroupUser.find_by(user_id: current_user.id,group_id: params[:id])
      user_room.destroy
      redirect_to groups_path
    else
    end
  end
  def show
    @group = Group.find(params[:id])
    @book = Book.new
  end
  def index
    @groups = Group.all
    @book = Book.new
  end
  def edit
    @group = Group.find(params[:id])
  end
  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    redirect_to groups_path
  end
  private
  def group_params
    params.require(:group).permit(:name,:introduction,:group_image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/edit.html.erb
<h1>Group Edit</h1>
<%= form_with model: @group do |f| %>
  <label>グループ名</label><br>
  <%= f.text_field :name %><br>
  <label>説明</label><br>
  <%= f.text_area :introduction %><br>
  <label>グループ画像</label><br>
  <%= f.file_field :group_image,accept:"image/jpg" %><br>
  <%= f.submit"保存" %>
<% end %>

app/views/groups/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
     <h2>User info</h2>
     <%= render 'users/info', user: current_user %>
     <h2 class="mt-3">New book</h2>
     <%= render 'books/form',book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
   <h1>Group一覧</h1>
    <table class="table">
      <% @groups.each do |group| %>
        <tr>
          <td><%= image_tag group.get_group_image(100,100) %></td>
          <td>
            <%= link_to group_path(group.id) do %>
               <%= group.name %>
            <% end %>
          </td>
          <td><%= group.introduction %></td>
          <% if group.owner_id == current_user.id %>
          <td><%= link_to"Edit",edit_group_path(group.id) %></td>
          <% else %>
          <td></td>
      <% end %>
      <td>メンバー：<%= group.users.count %></td>
    </tr>
  <% end %>
</table>
</div>

app/views/groups/new.html.erb
<h1>グループ作成画面</h1>
<%= form_with model: @group,name:"aaa" do |f| %>
  <label>グループ名</label><br>
  <%= f.text_field :name %><br>
  <label>説明</label><br>
  <%= f.text_area :introduction %><br>
  <label>グループ画像</label><br>
  <%= f.file_field :group_image,accept:"image/jpg" %><br>
  <%= f.submit"保存" %>
<% end %>

app/views/groups/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
     <h2>User info</h2>
     <%= render 'users/info', user: current_user %>
     <h2 class="mt-3">New book</h2>
     <%= render 'books/form',book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
   <h1>Group Datail</h1>
   <table class="table">
     <tr>
       <td><%= image_tag @group.get_group_image(100,100) %></td>
       <td><%= @group.name %></td>
       <td><%= @group.introduction %></td>
       <td>
         <% @group.users.each do |user| %>
          <li><%= user.name %></li>
         <% end %>
       </td>
       <% if @group.owner_id == current_user.id %>
         <td><%= link_to"Edit",edit_group_path(@group.id) %></td>
       <% end %>
       <% unless @group.users.exists?(id: current_user.id) %>
         <td><%= link_to"Join this group",groups_path(:group=>@group,:key=>"value"),method: :post,class:"btn btn-success" %></td>
       <% else %>
         <% unless @group.owner_id == current_user.id %>
           <td><%= link_to"Leave this group",group_path(@group.id,:key=>"value"),method: :delete,class:"btn btn-danger" %></td>
         <% else %>
           <td>あなたがオーナーです</td>
         <% end %>
       <% end %>
       </td>
     </tr>
   </table>
  </div>