config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get '/search', to: 'searches#searche'
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource:favorites,only:[:create, :destroy]
    resources:book_comments,only:[:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource:relationship,only:[:create, :destroy]
    get "relationships/follow_list"
    get "relationships/follower_list"
  end
  resources :chats, only: [:show,:create]

  resources:groups,only:[:new,:create,:index,:edit,:update,:show,:destroy]
  # get '/search'=>'searches#search',as:"search"
  # get '/search', to: 'searchs#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  belongs_to:user
  has_many:favorites,dependent: :destroy
  has_many:like_user,through: :favorites,source: :user

  has_many:book_comments,dependent: :destroy
  # def get_profile_image
  #   (profile_image.attached?) ? profile_image : 'no_image.jpg'
  # end


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to:user
  belongs_to:book
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to:user
  belongs_to:room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to:user
  belongs_to:book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many:group_users,dependent: :destroy
  has_many:users,through: :group_users
  has_one_attached:group_image
  def get_group_image(width,height)
    unless group_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      group_image.attach(io:File.open(file_path),filename:"default-image.jpg",content_type:"image/jpg")
    end
      group_image.variant(resize_to_limit:[width,height]).processed
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to:user
  belongs_to:group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to:follower,class_name: "User"
  belongs_to:followed,class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many:chats,dependent: :destroy
  has_many:user_rooms,dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:books,dependent: :destroy
  has_many:favorites,dependent: :destroy
  has_many:book_comments,dependent: :destroy

  has_many:follower,class_name: "Relationship" , foreign_key: "follower_id",dependent: :destroy
  has_many:followed,class_name: "Relationship" , foreign_key: "followed_id",dependent: :destroy

  has_many:followers,through: :follower,source: :followed
  has_many:followeds,through: :followed,source: :follower

  has_many:group_users,dependent: :destroy
  has_many:groups,through: :group_users

  has_many:user_rooms,dependent: :destroy
  has_many:chats,dependent: :destroy

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,length:{ maximum: 50 }



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to:user
  belongs_to:room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit]
  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @books = Book.new
    @comment = BookComment.new
    @today_books = Book.where(created_at: Date.current)
  end

  def index
    to=Time.current
    from=(to - 6.day)
    @book = Book.new
    @books = Book.includes(:like_user).sort{|a,b|
     b.like_user.includes(:favorites).where(created_at: from...to).size <=>
     a.like_user.includes(:favorites).where(created_at: from...to).size}
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      @book = Book.new
      @books = Book.all
      redirect_to books_path
    end
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_room = UserRoom.find_by(user_id: @user.id,room_id: rooms)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    # to=Time.current
    # from=(to - 6.day)
    # created_at: Time.current-1.day...Time.current
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    # 今日投稿した数
    @today_books = @user.books.where(created_at: Time.zone.now.all_day)
    # 昨日投稿した数
    @yesterday_books = @user.books.where(created_at: Time.zone.now.yesterday.all_day)
    if  @today_books.count == 0 || @yesterday_books.count == 0
      @ratio="比較不可"
    else
      @ratio = (@today_books.count.to_f / @yesterday_books.count.to_f)*100
    end
    # 今週投稿した数
    @week = @user.books.where(created_at: Time.current.ago(1.week)...Time.current)
    # 先週投稿した数
    @week_second = @user.books.where(created_at: Time.current.ago(2.week)...Time.current.ago(1.week))
    if @week.count == 0 || @week_second.count == 0
      @week_ratio = "比較不可"
    else
      @week_ratio = @week.count.to_f / @week_second.count.to_f
    end
    number = params[:created_at]

    if number.present?
      @sort = @user.books.where(created_at: number.in_time_zone.all_day)
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model: book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size: '50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td id="favorite_btn_<%= book.id %>">
           <%= render"favorites/favorite",book: book %>
        </td>
        <td>
          コメント<%= book.book_comments.count %>件
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<% if @book.errors.any? %>
        <%= @book.errors.count %>件のerror発生
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      <% end %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>

      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <% if @book.errors.any? %>
       <%= @book.errors.count %>件のerror
       <% @book.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
      <% end %>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @books %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td id="favorite_btn_<%= @book.id %>">
            <%= render"favorites/favorite",book: @book %>
          </td>
            <td>
              <% if @book.user_id == current_user.id %>
                <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %>
              <% end %>
            </td>
            <td>
              <% if @book.user_id == current_user.id %>
                <%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%>
              <% end %>
            </td>
            <td>
              コメント<%= @book.book_comments.count %>件
            </td>

        </tr>
      </table>
      <h3>コメント一覧</h3>
      <table class="table comment_list">
        <%= render"book_comments/book_comment",book: @book %>
      </table>
      <div class="form">
        <%= render"book_comments/form",comment: @comment,book: @book %>
      </div>
    </div>
  </div>
</div>

app/views/chats/show.html.erb
<h1>Chats#show</h1>
<p>Find me in app/views/chats/show.html.erb</p>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数<%= user.follower.count %></td>
        <td>フォロワー数<%= user.followed.count %></td>
        <% unless user.id == current_user.id %>
          <% if current_user.follower.exists?(followed_id: user.id) %>
            <td><%= link_to "フォロー解除",user_relationship_path(user.id),method: :delete %></td>
          <% else %>
            <td><%= link_to "フォロー",user_relationship_path(user.id),method: :post %></td>
          <% end %>
        <% else %>
            <td></td>
        <% end %>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th></th>
    <th>
      <%= link_to user_relationships_follow_list_path(user.id) do %>
        フォロー<%= user.followers.count %>件
      <% end %>
    </th>
  </tr>
  <tr>
    <th></th>
    <th>
      <%= link_to user_relationships_follower_list_path(user.id) do %>
        フォロワー<%= user.followeds.count %>件
      <% end %>
    </th>
  </tr>
</table>
  <% unless current_user.id == user.id %>
    <% if current_user.follower.exists?(followed_id: user.id) %>
      <buton class="btn btn-success mb-4"><%= link_to"フォロー解除",user_relationship_path(user.id),method: :delete,class:"text-white" %></buton>
    <% else %>
      <buton class="btn btn-success mb-4"><%= link_to"フォロー",user_relationship_path(user.id),method: :post,class:"text-white" %></buton>
    <% end %>
  <% end %>


<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>

     <div class="form-group">
        <%= f.label :profile_image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
     <h2>User info</h2>
     <%= render 'info', user: current_user %>
     <h2 class="mt-3">New book</h2>
     <%= render 'books/form',book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
     <h2>Users</h2>
     <%= link_to"グループ作成",new_group_path %>
     <%= link_to"グループ一覧",groups_path %>
     <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>

      <h3>検索</h3>
      <%= form_with url: user_path(@user.id),method: :get,local: false do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit"検索" %>
      <% end %>
      <div id="time">
        <%= render"searches/searchtime",sort: @sort %>
      </div>

      <h3>投稿数の前日比、前週比</h3>
      <table class="table">
        <tr>
          <td>今日の投稿数</td>
          <td>前日の投稿数</td>
          <td>前日比</td>
        </tr>
        <tr>
          <td><%= @today_books.count %></td>
          <td><%= @yesterday_books.count %></td>
          <td><%= @ratio %>%</td>
        </tr>
        <tr>
          <td>今週の投稿数</td>
          <td>先週の投稿数</td>
          <td>前週比</td>
        </tr>
        <tr>
          <td><%= @week.count %></td>
          <td><%= @week_second.count %></td>
          <td><%= @week_ratio %></td>
        </tr>
      </table>

      <h3>過去７日間の推移</h3>
      <table class="table">
        <tr>
          <td>６日前</td>
          <td>５日前</td>
          <td>４日前</td>
          <td>３日前</td>
          <td>２日前</td>
          <td>１日前</td>
          <td>今日</td>
        </tr>
        <tr>
          <td><%= @user.books.where(created_at: Time.zone.now.ago(6.day).all_day).count %></td>
          <td><%= @user.books.where(created_at: Time.zone.now.ago(5.day).all_day).count %></td>
          <td><%= @user.books.where(created_at: Time.zone.now.ago(4.day).all_day).count %></td>
          <td><%= @user.books.where(created_at: Time.zone.now.ago(3.day).all_day).count %></td>
          <td><%= @user.books.where(created_at: Time.zone.now.ago(2.day).all_day).count %></td>
          <td><%= @user.books.where(created_at: Time.zone.now.ago(1.day).all_day).count %></td>
          <td><%= @user.books.where(created_at: Time.zone.now.all_day).count %></td>
        </tr>
      </table>
      <div>
        <canvas id="mychart"></canvas>
      </div>
      <script>
       var ctx = document.getElementById('mychart');
       var myChart = new Chart(ctx, {
         type: 'line',
         data: {

           labels: ['今日', '１日前', '２日前', '３日前', '４日前', '５日前', '６日前'],
           datasets: [{
             label: '投稿した本の数',
             data: [<%= @user.books.where(created_at: Time.zone.now.all_day).count %>,
                    <%= @user.books.where(created_at: Time.zone.now.ago(1.day).all_day).count %>,
                    <%= @user.books.where(created_at: Time.zone.now.ago(2.day).all_day).count %>,
                    <%= @user.books.where(created_at: Time.zone.now.ago(3.day).all_day).count %>,
                    <%= @user.books.where(created_at: Time.zone.now.ago(4.day).all_day).count %>,
                    <%= @user.books.where(created_at: Time.zone.now.ago(5.day).all_day).count %>,
                    <%= @user.books.where(created_at: Time.zone.now.ago(6.day).all_day).count %>,
            ],
             borderColor: '#f88',
           }],
        　 },
         options: {
           y: {
             min: 0,
             max: 10,
           },
         },
       });
</script>
    </div>

  </div>
</div>

app/views/users/show.js.erb
$("#time").html("<%= j(render "searches/searchtime",sort: @sort) %>")